
import Wrapper from '../Wrapper'
import WrappedComponents from './WrappedComponents'

export const allDecorOptions = [
  {
    id: 1,
    slug: "simple-balloon-decor",
    name: "Simple Balloon Decor for Home",
    mrp: "₹1999",
    salePrice: "₹1499",
    salePercentage: "25%",
    src: "birthday1.webp",
    rating: "4.9",
    reviews: "487",
    category: "birthday",
  },
  {
    id: 2,
    slug: "rose-gold-birthday-decor",
    name: "Rose Gold Birthday Home Decor",
    mrp: "₹2299",
    salePrice: "₹1999",
    salePercentage: "13%",
    src: "birthday2.webp",
    rating: "4.9",
    reviews: "352",
    category: "birthday",
  }, {
    id: 3,
    slug: "adorable-birthday-arch",
    name: "Adorable Birthday Arch Backdrop",
    mrp: "₹3299",
    salePrice: "₹2499",
    salePercentage: "24%",
    src: "birthday3.webp",
    rating: "5",
    reviews: "325",
    category: "birthday",
  }, {
    id: 4,
    slug: "blush-glow-birthday-theme",
    name: "Blush & Glow Birthday Theme",
    mrp: "₹2499",
    salePrice: "₹2199",
    salePercentage: "12%",
    src: "birthday4.webp",
    rating: "4.9",
    reviews: "287",
    category: "birthday",
  }, {
    id: 5,
    slug: "anniversay-home-decoration",
    name: "Anniversary Home Decoration",
    mrp: "₹2199",
    salePrice: "₹1999",
    salePercentage: "9%",
    src: "anniversary1.webp",
    rating: "4.9",
    reviews: "487",
    category: "anniversary",
  }, {
    id: 6,
    slug: "red-anniversary-home-decor",
    name: "Red Anniversary Home Decor",
    mrp: "₹2499",
    salePrice: "₹2099",
    salePercentage: "16%",
    src: "anniversary2.webp",
    rating: "4.8",
    reviews: "185",
    category: "anniversary",
  }, {
    id: 7,
    slug: "romantic-anniversary-room-decor",
    name: "Romantic Anniversary Room Celebration",
    mrp: "₹2499",
    salePrice: "₹2399",
    salePercentage: "4%",
    src: "anniversary3.webp",
    rating: "4.4",
    reviews: "23",
    category: "anniversary",
  }, {
    id: 8,
    slug: "anniversary-bliss-setup",
    name: "Anniversary Bliss Setup",
    mrp: "₹2999",
    salePrice: "₹2499",
    salePercentage: "17%",
    src: "anniversary4.webp",
    rating: "4.6",
    reviews: "255",
    category: "anniversary",
  }, {
    id: 9,
    slug: "dreamy-baby-shower-balloons",
    name: "Dreamy Baby Shower Balloons",
    mrp: "₹3299",
    salePrice: "₹2999",
    salePercentage: "9%",
    src: "baby-shower1.webp",
    rating: "4.6",
    reviews: "187",
    category: "baby-shower",
  }, {
    id: 10,
    slug: "baby-homecoming-setup",
    name: "Baby Homecoming Setup",
    mrp: "₹4499",
    salePrice: "₹3899",
    salePercentage: "13%",
    src: "baby-shower2.webp",
    rating: "4.9",
    reviews: "352",
    category: "baby-shower",
  }, {
    id: 11,
    slug: "welcome-balloon-setup",
    name: "Welcome Balloon Setup",
    mrp: "₹2399",
    salePrice: "₹1999",
    salePercentage: "17%",
    src: "baby-shower3.webp",
    rating: "5",
    reviews: "325",
    category: "baby-shower",
  }, {
    id: 12,
    slug: "simple-welcome-balloon-decoration",
    name: "Simple Welcome Balloon Decoration",
    mrp: "₹2099",
    salePrice: "₹1699",
    salePercentage: "19%",
    src: "baby-shower4.webp",
    rating: "4.9",
    reviews: "287",
    category: "baby-shower",
  },
  {
    id: 13,
    slug: "bride-to-be-party-decoration",
    name: "Bride to be Party Decoration",
    mrp: "₹2799",
    salePrice: "₹2599",
    salePercentage: "7%",
    src: "bachelorette1.webp",
    rating: "4.6",
    reviews: "130",
    category: "bachelorette",
  },
  {
    id: 14,
    slug: "bride-to-be-ring-decoration",
    name: "Bride to be Ring Decoration",
    mrp: "₹7499",
    salePrice: "₹6999",
    salePercentage: "7%",
    src: "bachelorette2.webp",
    rating: "4.8",
    reviews: "85",
    category: "bachelorette",
  },
  {
    id: 15,
    slug: "simple-bachelorette-wall-arch",
    name: "Simple Bachelorette Wall Arch",
    mrp: "₹2699",
    salePrice: "₹2299",
    salePercentage: "15%",
    src: "bachelorette3.webp",
    rating: "4.9",
    reviews: "13",
    category: "bachelorette",
  },
  {
    id: 16,
    slug: "simple-bachelorette-decoration",
    name: "Simple Bachelorette Decoration",
    mrp: "₹2099",
    salePrice: "₹1799",
    salePercentage: "14%",
    src: "bachelorette4.webp",
    rating: "4.6",
    reviews: "91",
    category: "bachelorette",
  },
  {
    id: 17,
    slug: "audi-rose-car-decor",
    name: "Audi Rose Bridal Car Decoration",
    mrp: "₹5499",
    salePrice: "₹4799",
    salePercentage: "13%",
    src: "cardecor1.webp",
    rating: "4.9",
    reviews: "44",
    category: "cardecor",
  },
  {
    id: 18,
    slug: "premium-wedding-car-decor",
    name: "Premium Wedding Car Decoration",
    mrp: "₹13999",
    salePrice: "₹11999",
    salePercentage: "14%",
    src: "cardecor2.webp",
    rating: "4.7",
    reviews: "85",
    category: "cardecor",
  },
  {
    id: 19,
    slug: "bridal-toyota-car-decor",
    name: "Bridal Toyota Car Decoration",
    mrp: "₹5499",
    salePrice: "₹4399",
    salePercentage: "20%",
    src: "cardecor3.webp",
    rating: "4.6",
    reviews: "32",
    category: "cardecor",
  }, {
    id: 20,
    slug: "white-car-wedding-decor",
    name: "White Car Wedding Decoration",
    mrp: "₹10999",
    salePrice: "₹9999",
    salePercentage: "9%",
    src: "cardecor4.webp",
    rating: "4.7",
    reviews: "71",
    category: "cardecor",
  }, {
    id: 21,
    slug: "cafe-opening-entrance-decoration",
    name: "Cafe Opening Entrance Decoration",
    mrp: "₹4099",
    salePrice: "₹3199",
    salePercentage: "22%",
    src: "shopdecor1.webp",
    rating: "4.4",
    reviews: "45",
    category: "shopdecor",
  }, {
    id: 22,
    slug: "entrance-balloon-gate-for-shop-opening",
    name: "Entrance Balloon Gate for Shop Opening",
    mrp: "₹6999",
    salePrice: "₹5499",
    salePercentage: "21%",
    src: "shopdecor2.webp",
    rating: "4.8",
    reviews: "78",
    category: "shopdecor",
  }, {
    id: 23,
    slug: "corporate-gala-balloon-decoration",
    name: "Corporate Gala Balloon Decoration",
    mrp: "₹12999",
    salePrice: "₹10999",
    salePercentage: "15%",
    src: "shopdecor3.webp",
    rating: "4.2",
    reviews: "30",
    category: "shopdecor",
  }, {
    id: 24,
    slug: "shop-opening-decoration",
    name: "Shop Opening Decoration",
    mrp: "₹3699",
    salePrice: "₹2999",
    salePercentage: "19%",
    src: "shopdecor4.webp",
    rating: "4.6",
    reviews: "84",
    category: "shopdecor",
  }, {
    id: 25,
    slug: "welcome-baby-princess-decoration",
    name: "Welcome Baby Princess Decoration",
    mrp: "₹4499",
    salePrice: "₹3899",
    salePercentage: "13%",
    src: "welcome-baby1.webp",
    rating: "4.9",
    reviews: "487",
    category: "welcomebaby",
  }, {
    id: 26,
    slug: "baby-homecoming-setup",
    name: "Baby Homecoming Setup",
    mrp: "₹4499",
    salePrice: "₹3899",
    salePercentage: "13%",
    src: "welcome-baby2.webp",
    rating: "4.9",
    reviews: "352",
    category: "welcomebaby",
  }, {
    id: 27,
    slug: "welcome-balloon-setup",
    name: "Welcome Balloon Setup",
    mrp: "₹2399",
    salePrice: "₹1999",
    salePercentage: "17%",
    src: "welcome-baby3.webp",
    rating: "5",
    reviews: "325",
    category: "welcomebaby",
  }, {
    id: 28,
    slug: "simple-welcome-balloon-decoration",
    name: "Simple Welcome Balloon Decoration",
    mrp: "₹2099",
    salePrice: "₹1699",
    salePercentage: "19%",
    src: "welcome-baby4.webp",
    rating: "4.9",
    reviews: "287",
    category: "welcomebaby",
  }
]
const Home = () => {
  return (
    <>
      <Wrapper>
        <WrappedComponents />
      </Wrapper>
    </>
  )
}

export default Home
